### ISSUE TITLE
[question] Should we start using WAT2 or stick at WAT for now?

### ISSUE THREAD

**Issue by BtM909** [D4koon/WhatsappTray2#3]
The title says it all :)

I'm currently using WAT and wanted to report a few things, but would it make sense to just switch to WAT2 and start raising topics for this repo?

Talk soon

**Comment by D4koon** [comment]
I will not put more work into WhatsappTray1 so i guess its better to switch 😃 .

**Comment by BtM909** [comment]
Haha, ok!

Befor eyou close, Where do I download the latest release?

**Comment by D4koon** [comment]
Always under releases :)
https://github.com/D4koon/WhatsappTray2/releases
