### ISSUE TITLE
message conunter

### ISSUE THREAD

**Issue by kosmic0** [D4koon/WhatsappTray2#4]
message counter always displaying -1
windows 7

**Comment by D4koon** [comment]
What version of Whatsapptray are you using?
Resently they change something in their API but i already made an update and released it.
https://github.com/D4koon/WhatsappTray2/releases/tag/2.1.0.0

**Comment by kosmic0** [comment]
2.0.1.0  thanxxxxx will get the 2.1.0.0   much love <3
